services:
  db:
    image: postgres:16
    container_name: pg-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cHJvcGVyeW91bmdlcmV4YWN0bHlzaGFraW5nc2hvdG15c3RlcmlvdXNjdXN0b21zYmU=
      POSTGRES_DB: kan-ban
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      

volumes:
  pgdata: 
  redisdata:  